application: lateral-array-468
version: 2
runtime: go
api_version: go1

handlers:
    - url: /index.html
      static_files: index.html
      application_readable: true
      upload: index.html

    - url: /.* 
      script: _go_app


